### PR TITLE
Add possibility to specify Cache-Control: max-age=.. for uploaded files

### PR DESCRIPTION
**Pull request by vrobik**
Hi @shishirsharma 

can you please add this possibility for file uploads?
i make a quick change and build -prod worked well

Thanks

### CODE REVIEW

**Comment by shishirsharma** [comment]
@vrobik Thanks for the PR, I will review this today and will let you know.

**Comment by shishirsharma** [comment]
This looks good. Unfortunately Master currently under development for V2. The current production version is in https://github.com/shishirsharma/MyS3Browser/tree/version-1 branch. If you can open a new PR with this code to this Version-1 branch, I can release this tomorrow.

Or I will do that for you.

**Comment by vrobik** [comment]
Hi @shishirsharma 
i don't see version-1 in list of available branches to merge code with it, so i create PR directly
hope will not have conflicts 😁

**Comment by shishirsharma** [comment]
Some features in the master branch are not yet complete. 
Merging it with master will not Release it on Chrome Store. Chrome Store code is on V1 at this point. V1 is not compatible with changes in Master. 

So basically Master is ahead of V1 and This has to be fixed in V1 if you want this to be made available to users/friends. 

Thanks for the work anyway.

**Pull request closed without merging**
